### ISSUE TITLE
Paths without drive letter are not detected (on Windows)

### ISSUE THREAD

**Issue by markahon** [bluesliverx/grails-external-config-reload#25]
The following does *not* work

    file:///some/path/to/file...

This works

    file://\\C:/some/path/to/file...

**Comment by bluesliverx** [comment]
Apologies, I never got a notification about this and I don't monitor this repo.  I'm honestly not sure what we could do about your problem except to make it clearer in docs that on windows you must include the full path.

**Comment by markahon** [comment]
Heh, it's been quite a while since this occurred, but no worries. I guess just a mention in the readme would suffice. This issue can also be just closed as far as I'm concerned.
