### ISSUE TITLE
Support Grails 3

### ISSUE THREAD

**Issue by dtanner** [bluesliverx/grails-external-config-reload#28]
Hi,
Any thoughts/plans on supporting grails 3?  Thanks.

**Comment by bluesliverx** [comment]
I haven't even looked at grails 3 yet to be honest.  I may in the next couple of months, however, and this plugin would definitely be one I ported.

**Comment by dtanner** [comment]
Sounds good - thanks.  I finally got around to porting one myself; it was about a handful of hours for a plugin that didn't need any code changes outside of the necessary grails infrastructure changes (jasypt-encryption).

**Comment by bluesliverx** [comment]
Any chance for a pull request? :)

**Comment by dtanner** [comment]
Sure - I'll give it a whirl.

**Comment by bluesliverx** [comment]
Thanks!

**Comment by dtanner** [comment]
Hey just a quick update - I made the changes and things appear to be working.  I have a question out on if there's a slick way to parse YAML into a ConfigObject now that it's the default way to handle config for Grails.  It'd be nice to let people define config in either groovy or YAML.  If it's a PITA for now though, I'll submit the PR as-is and go from there.

**Comment by bluesliverx** [comment]
I'm not aware of one, but it shouldn't be too hard to write.  It would just be finding or using a YAML parser and then iterating through all of the keys and constructing the config object from there.  Simple, but not trivial probably.

**Comment by dtanner** [comment]
closing this - handled by the PR
