### ISSUE TITLE
Initial external config load does not happen

### ISSUE THREAD

**Issue by jglapa** [bluesliverx/grails-external-config-reload#30]
Hi I've just run into situation where my external properties where not loaded after server restart. The reason why is this line:
https://github.com/bluesliverx/grails-external-config-reload/blob/master/grails-app/services/grails/plugins/reloadconfig/ReloadConfigService.groovy#L44

`if (configFile.exists() && configFile.lastModified()>lastTimeChecked.time) {`
So when I do some changes to my external config while the app is running it's ok because the lastModified date will greater than lastTimeChecked so the reload will trigger. But If I have to restart my app this won't trigger b/c the lastTimeChecked will be initially set to new Date() which is later than my last config update.

Can we add the `reloadConfigService.reloadNow()` execution at the end of the `doWithApplicationContext` closure in plugin setup. 
This should solve the problem I guess?
I can also prepare a PR and make it configurable via property if desired.

As a workaround I'll now call the  `reloadConfigService.reloadNow()` from my Bootstrap.groovy

**Comment by bluesliverx** [comment]
Calling reloadNow is not the right solution to this problem as all external config should be reloaded automatically when the app starts.  When you say "server restart", what exactly do you mean?  What do your config locations look like?

It's been a long time since I've even looked at this plugin, so I admit I may be missing something, but if you are defining the grails.config.locations (or whatever that parameter is called) with your external config files, grails itself should be the one that manages loading them initially.  This plugin just handles situations where they change after start.

**Comment by dtanner** [comment]
IIRC the concept of Grails' config.locations isn't supported out of the box any more.  I did add the call to `checkNow(true)` (to force the reload)  as the 2nd to last line in doWithApplicationContext to fix that change as part of my PR. i.e. What you suggested is what I did, although it wasn't the absolute last line in the method.  I'm pretty sure it was working for me locally.  So @jglapa I'm curious about what you mean by server restart too.  Does it work for you initially when the server starts, and then doesn't after some change?

**Comment by jglapa** [comment]
Hey @dtanner  @bluesliverx by server restart I mean a Tomcat restart with the grails app deployed in it.
My external file config is configured via this property:
`grails.plugins.reloadConfig.files = ['file:/opt/myApp/reloadableConfig.groovy']`

I'm not using the config.locations, `includeConfigLocations` is set to false

I'm using Grails 245

**Comment by bluesliverx** [comment]
@jglapa, that is the problem.  Since you are not including them in `grails.config.locations`, grails knows nothing about them on startup.  I would suggest changing `grails.plugins.reloadConfig.files` to `grails.config.locations`.

**Comment by jglapa** [comment]
@bluesliverx I'm already using `grails.config.locations` for some config overrides that are required when the app starts. The problem is that the properties there are not 'safe' to reload e.g. database connection parameters etc. in my `reloadableConfig.groovy` I want to keep properties that are not problematic to merge with the main Config.

**Comment by bluesliverx** [comment]
In that case, I would add a reloadNow call in your bootstrap before the app finishes starting.  Apparently I at least partially addressed this use case by allowing for the reload on change, but didn't fully address it by including a call to checkNow for just the files specified and not grails.config.locations*.  At this point, however, it is a simple workaround and I just don't have the time to make the change and figure out how to republish the plugin as my build system only existed at a previous job.  Sorry for not a great answer.

**Comment by bluesliverx** [comment]
This is fixed in the grails 3 version that will be published at some point soon, but that obviously doesn't help you as you are on 2.4.5

**Comment by jglapa** [comment]
@bluesliverx sure. The Bootstrap call seems to be working fine. Thanks for looking into it!
