### ISSUE TITLE
v2.0.0 plugin size

### ISSUE THREAD

**Issue by jglapa** [bluesliverx/grails-external-config-reload#31]
The plugin in current form is `40MB` 😮 
https://bintray.com/bluesliverx/grails-plugins/org.grails.plugins%3Aexternal-config-reload/2.0.0#files/org/grails/plugins/external-config-reload/2.0.0

**Comment by bluesliverx** [comment]
I'd have to check to see what process is actually including all of the jars, but I would guess it's in the grails builds.  It looks like gs-collections and groovy and all of the spring libraries are the biggest ones.  I'm sure we don't need all of those in order for grails to work.  I don't have time to look at this more, but I'm open to PRs if you figure out the process that is trying to build an uber jar.

**Comment by bluesliverx** [comment]
2.0.1 is released:
https://bintray.com/bluesliverx/grails-plugins/org.grails.plugins%3Aexternal-config-reload/2.0.1#files/org/grails/plugins/external-config-reload/2.0.1

<68k! Thanks for the help!
