### ISSUE TITLE
Trying to use 2.0.1... not in the repository?

### ISSUE THREAD

**Issue by paulbarker** [bluesliverx/grails-external-config-reload#35]
Hi,

I'm trying to use the 2.0.1 version on a Grails 3.2.13 application but I can't seem to get anything past version 1.4.1 from the repository.
I've also tried building the plugin as an 'inline' (i.e. multi-project gradle build) but it won't build (looks like Gradle incompatibilities with a dependency).

Is there a published version of 2.0.1 somewhere other than the usual grails repos or is the 'inline' the only way of getting it running now?

Thanks.

Paul.

**Comment by bluesliverx** [comment]
It's been so long since I used this, it took me awhile to find.  You can get it here: https://bintray.com/bluesliverx/grails-plugins/org.grails.plugins%3Aexternal-config-reload

**Comment by paulbarker** [comment]
Thank you so much! Saved me a real headache!
